/**
 * TriggerPlugin interface + associated event + config types.
 * Canonical location — schema.ts imports GitHubTriggerConfig, PerforceTriggerConfig,
 * and TriggerConfig from here (D-01, D-10, D-14, D-15).
 */
import type { FastifyRequest } from 'fastify';

/* ---------- Verify result ---------- */

export interface VerifySuccess {
  ok: true;
  /** X-GitHub-Delivery or body.delivery_id or a generated UUID for legacy senders. */
  deliveryId: string;
}

export interface VerifyFailure {
  ok: false;
  reason: 'signature_missing' | 'signature_mismatch' | 'token_mismatch' | 'header_missing';
}

export type VerifyResult = VerifySuccess | VerifyFailure;

/* ---------- GitHub events (D-09) ---------- */

export interface GitHubPushEvent {
  kind: 'push';
  ref: string; // e.g. 'refs/heads/main'
  repository: string; // repository.full_name e.g. 'acme/infra'
  sha: string; // head_commit.id (empty string if deleted ref)
  pusher: string; // pusher.name
  message: string; // head_commit.message
}

export interface GitHubPullRequestEvent {
  kind: 'pull_request';
  action: 'opened' | 'synchronize' | 'closed' | 'reopened';
  repository: string;
  number: number;
  headRef: string;
  baseRef: string;
  title: string;
}

export type GitHubEvent = GitHubPushEvent | GitHubPullRequestEvent;

/* ---------- Perforce event (D-14) ---------- */

export interface PerforceEvent {
  kind: 'perforce_change';
  change: string;
  user: string;
  client: string;
  root: string;
  depot: string;
  /** UUID generated by xci-emit script (D-24); auto-generated if absent. */
  deliveryId: string;
}

/* ---------- Trigger configs (D-10, D-15) — canonical, imported by schema.ts ---------- */

export interface GitHubTriggerConfig {
  plugin: 'github';
  events: Array<'push' | 'pull_request'>;
  repository?: string; // glob e.g. 'acme/*' or 'acme/infra'
  branch?: string; // glob e.g. 'main', 'release/*'
  actions?: Array<'opened' | 'synchronize' | 'closed' | 'reopened'>; // PR only
}

export interface PerforceTriggerConfig {
  plugin: 'perforce';
  depot?: string; // glob e.g. '//depot/infra/*'
  user?: string; // glob
  client?: string; // glob
}

export type TriggerConfig = GitHubTriggerConfig | PerforceTriggerConfig;

/* ---------- mapToTask result ---------- */

export interface TaskTriggerMatch {
  taskId: string;
  params: Record<string, string>;
}

/* ---------- TriggerPlugin interface (D-01, PLUG-01) ---------- */

/**
 * Each bundled plugin implements this 3-method interface.
 * The generic parameter `E` is the typed event emitted by parse().
 * The shared webhook route handler (Plan 12-03) uses TriggerPlugin<unknown>
 * for the registry lookup, then delegates verify/parse/mapToTask to the
 * concrete plugin without needing to know the event type.
 */
export interface TriggerPlugin<E = unknown> {
  /** Unique name — matches the URL path segment and the registry key. */
  name: 'github' | 'perforce';

  /**
   * Verifies the request's authenticity.
   * - GitHub: computes HMAC-SHA256 of rawBody with pluginSecret, compares
   *   against X-Hub-Signature-256 header via timingSafeEqual.
   * - Perforce: checks X-Xci-Token header presence; token comparison is
   *   done at the route layer (Plan 12-03). pluginSecret may be null here.
   *
   * Must NEVER throw — returns a typed VerifyResult instead.
   * SECURITY: pluginSecret Buffer must not be logged, serialized, or included in errors.
   */
  verify(req: FastifyRequest, pluginSecret: Buffer | null): VerifyResult;

  /**
   * Parses req.body + req.headers into a typed event.
   * Returns null for valid-but-ignored events (GitHub 'issues', 'workflow_run' etc.).
   * Throws on malformed body — caller routes to DLQ with reason 'parse_failed'.
   */
  parse(req: FastifyRequest): E | null;

  /**
   * Matches the event against the array of trigger configs.
   * Returns ALL matches (one event can fire multiple tasks).
   * The caller (Plan 12-03 route handler) pre-scopes `candidates` to the resolved org's
   * tasks — this plugin is org-agnostic (T-12-02-06 mitigation: caller's responsibility).
   */
  mapToTask(
    event: E,
    candidates: Array<{ taskId: string; configs: TriggerConfig[] }>,
  ): TaskTriggerMatch[];
}
