// packages/xci/src/perforce-emitter.ts
// Plan 12-05 Task 1 — Perforce trigger script emitter
//
// Emits 3 Node-free trigger scripts (sh/bat/ps1) for use as Perforce change-commit triggers.
// Generated scripts POST a JSON payload to the xci webhook endpoint using curl / Invoke-WebRequest.
// No Node.js required on the Perforce server.
//
// SECURITY: Generated scripts contain the webhook token inline.
// Set file mode 0o700 on POSIX (chmod 700) and use icacls on Windows to restrict access.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface EmitOptions {
  /** Webhook endpoint URL, e.g. https://xci.example.com/hooks/perforce/xci_whk_abc */
  url: string;
  /** X-Xci-Token header value (the orgToken plaintext from webhook_tokens) */
  token: string;
  /** Target directory for the 3 generated files */
  outputDir: string;
}

export interface EmitResult {
  /** Relative filenames written to outputDir */
  readonly files: readonly string[];
}

// ---------------------------------------------------------------------------
// Token format validation (T-12-05-05)
// ---------------------------------------------------------------------------

// xci tokens are base64url charset: A-Za-z0-9 + _ + / + + = -
// Reject anything outside this set to prevent shell injection.
const SAFE_TOKEN_RE = /^[A-Za-z0-9_+/=\-]+$/;

function validateToken(token: string): void {
  if (!SAFE_TOKEN_RE.test(token)) {
    const err = new Error(
      `InvalidTokenFormatError: Token contains unsafe characters. ` +
        `Expected base64url charset (A-Za-z0-9_+/=-). Got: ${JSON.stringify(token.slice(0, 20))}`
    );
    err.name = 'InvalidTokenFormatError';
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Comment headers
// ---------------------------------------------------------------------------

function headerSh(url: string): string {
  return `#!/bin/sh
#
# xci Perforce change-commit trigger — POSIX shell
# Generated by: xci agent-emit-perforce-trigger
# Endpoint: ${url}
#
# Install as a Perforce change-commit trigger:
#   p4 triggers
#   Add line: xci-trigger change-commit //... "/path/to/trigger.sh %change% %user% %client%"
#
# SECURITY: This script contains the webhook token inline.
# Guard this file — it contains your webhook token.
# Restrict file permissions on the Perforce server:
#   chmod 700 trigger.sh
#   chown <p4_service_user> trigger.sh
`;
}

function headerBat(url: string): string {
  return `@echo off
REM xci Perforce change-commit trigger - Windows cmd wrapper
REM Generated by: xci agent-emit-perforce-trigger
REM Endpoint: ${url}
REM
REM Guard this file — it contains your webhook token.
REM Uses PowerShell under the hood (cmd has no native HTTP client).
REM SECURITY: restrict file permissions on the Perforce server:
REM   icacls trigger.bat /inheritance:r /grant:r "<P4 service account>:F"
`;
}

function headerPs1(url: string): string {
  return `# xci Perforce change-commit trigger - PowerShell
# Generated by: xci agent-emit-perforce-trigger
# Endpoint: ${url}
#
# Install as a Perforce change-commit trigger on Windows:
#   p4 triggers
#   Add line: xci-trigger change-commit //... "powershell -ExecutionPolicy Bypass -File C:\\path\\to\\trigger.ps1 %change% %user% %client%"
#
# Guard this file — it contains your webhook token.
# SECURITY: restrict file permissions (icacls) and store outside VCS-tracked directories.
`;
}

// ---------------------------------------------------------------------------
// Template builders
// ---------------------------------------------------------------------------

/**
 * Build the POSIX shell trigger script.
 * Uses curl for HTTP; generates a UUID delivery_id for idempotency.
 */
export function buildShTemplate(url: string, token: string): string {
  return `${headerSh(url)}
set -e

# Generate a UUID for delivery_id (for idempotency dedup per D-22)
if [ -r /proc/sys/kernel/random/uuid ]; then
  DELIVERY_ID=$(cat /proc/sys/kernel/random/uuid)
elif command -v uuidgen >/dev/null 2>&1; then
  DELIVERY_ID=$(uuidgen)
else
  DELIVERY_ID="$(date +%s)-$$"
fi

# Perforce change-commit environment variables (fallback to positional args)
CHANGE="\${P4_CHANGE:-\${1:-}}"
P4USER="\${P4_USER:-\${2:-}}"
CLIENT="\${P4_CLIENT:-\${3:-}}"
ROOT="\${P4_ROOT:-}"
DEPOT="\${P4_DEPOT_PATH:-}"

BODY="{\\"change\\":\\"\${CHANGE}\\",\\"user\\":\\"\${P4USER}\\",\\"client\\":\\"\${CLIENT}\\",\\"root\\":\\"\${ROOT}\\",\\"depot\\":\\"\${DEPOT}\\",\\"delivery_id\\":\\"\${DELIVERY_ID}\\"}"

curl --fail --silent --show-error \\
  -X POST \\
  -H "Content-Type: application/json" \\
  -H "X-Xci-Token: ${token}" \\
  --data-raw "\${BODY}" \\
  "${url}"
`;
}

/**
 * Build the PowerShell trigger script.
 * Uses Invoke-WebRequest; generates a UUID delivery_id via [guid]::NewGuid().
 */
export function buildPs1Template(url: string, token: string): string {
  return `${headerPs1(url)}
$ErrorActionPreference = 'Stop'

# Perforce change-commit environment variables (fallback to positional args)
$change = if ($env:P4_CHANGE) { $env:P4_CHANGE } elseif ($args.Count -ge 1) { $args[0] } else { '' }
$p4user = if ($env:P4_USER)   { $env:P4_USER }   elseif ($args.Count -ge 2) { $args[1] } else { '' }
$client = if ($env:P4_CLIENT) { $env:P4_CLIENT } elseif ($args.Count -ge 3) { $args[2] } else { '' }
$root   = if ($env:P4_ROOT)   { $env:P4_ROOT }   else { '' }
$depot  = if ($env:P4_DEPOT_PATH) { $env:P4_DEPOT_PATH } else { '' }
$deliveryId = [guid]::NewGuid().ToString()

$body = @{
  change      = $change
  user        = $p4user
  client      = $client
  root        = $root
  depot       = $depot
  delivery_id = $deliveryId
} | ConvertTo-Json -Compress

Invoke-WebRequest -Uri '${url}' -Method POST \`
  -Headers @{ 'X-Xci-Token' = '${token}'; 'Content-Type' = 'application/json' } \`
  -Body $body \`
  -UseBasicParsing | Out-Null
`;
}

/**
 * Build the Windows .bat trigger script.
 * Delegates to PowerShell (cmd has no native HTTP client).
 */
export function buildBatTemplate(url: string, token: string): string {
  return `${headerBat(url)}
setlocal
set "CHANGE=%P4_CHANGE%"
if "%CHANGE%"=="" set "CHANGE=%~1"
set "P4USER_=%P4_USER%"
if "%P4USER_%"=="" set "P4USER_=%~2"
set "CLIENT=%P4_CLIENT%"
if "%CLIENT%"=="" set "CLIENT=%~3"
set "ROOT=%P4_ROOT%"
set "DEPOT=%P4_DEPOT_PATH%"

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$body = @{ change='%CHANGE%'; user='%P4USER_%'; client='%CLIENT%'; root='%ROOT%'; depot='%DEPOT%'; delivery_id=[guid]::NewGuid().ToString() } | ConvertTo-Json -Compress;" ^
  "Invoke-WebRequest -Uri '${url}' -Method POST -Headers @{ 'X-Xci-Token'='${token}'; 'Content-Type'='application/json' } -Body $body -UseBasicParsing | Out-Null"

endlocal
`;
}

// ---------------------------------------------------------------------------
// Main emit function
// ---------------------------------------------------------------------------

/**
 * Generate 3 Perforce trigger scripts (sh/bat/ps1) in the target directory.
 * Files are written with mode 0o700 on POSIX (Windows NTFS uses ACLs — admin responsibility).
 *
 * @throws {InvalidTokenFormatError} if token contains shell-unsafe characters
 */
export function emitPerforceTriggerScripts(opts: EmitOptions): EmitResult {
  validateToken(opts.token);

  const out = resolve(opts.outputDir);
  mkdirSync(out, { recursive: true });

  const sh = buildShTemplate(opts.url, opts.token);
  const ps1 = buildPs1Template(opts.url, opts.token);
  const bat = buildBatTemplate(opts.url, opts.token);

  writeFileSync(join(out, 'trigger.sh'), sh, { mode: 0o700 });
  writeFileSync(join(out, 'trigger.bat'), bat, { mode: 0o700 });
  writeFileSync(join(out, 'trigger.ps1'), ps1, { mode: 0o700 });

  return { files: ['trigger.sh', 'trigger.bat', 'trigger.ps1'] };
}
